server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    resolver 127.0.0.11 valid=10s;          # Tell docker DNS, re-resolve every 10s
                                            # Essential due to docker-compose's internal DNS 
                                            # doesn't resolve container names to its assigned IPs at runtime, 
                                            # Which is bad for CD script that constantly recreates containers 
                                            # and updates their IPs.

    location / {
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        set $backend http://backend:8080;   # store IP in var to forces runtime resolve
        proxy_pass $backend;                # ~line 10: was `http://backend:8080`
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /ws {
        set $backend http://backend:8080;  
        proxy_pass $backend;                
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
